name: Already Aware
favicon: null
layout_spectrum: 0.25729
typography_spectrum: 0.43109
title: Already Aware
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242721'
    - '#006b00'
    - '#ffa600'
    - '#e4e684'
    - '#67819d'
  brandStrength: 0.12236608797684312
  lightness: 0.15863319369964302
  saturation: 0.6869022708851844
  rhythmicContrast: 0.5787777013611048
purpose: []
