name: Already Aware
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66053
title: Already Aware
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#ceb8b1'
    - '#231b1c'
    - '#ad5747'
    - '#fefeee'
  brandStrength: 0.1875
  lightness: 0.15863319369964302
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
