name: Already Aware
favicon: null
layout_spectrum: 0.31045560678467155
typography_spectrum: 0.26135
title: Already Aware
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12236608797684312
  lightness: 0.15863319369964302
  saturation: 0.6869022708851844
  rhythmicContrast: 0.5787777013611048
purpose: []
