name: Already Aware
favicon: null
layout_spectrum: 0
typography_spectrum: 0.43558
title: Already Aware
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1ae7b'
    - '#ff9f00'
    - '#552f00'
    - '#c58300'
    - '#c84d00'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
