name: Already Aware
favicon: null
layout_spectrum: 0.31045560678467155
typography_spectrum: 0.26135
title: Already Aware
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1ae7b'
    - '#ff9f00'
    - '#552f00'
    - '#c58300'
    - '#c84d00'
  brandStrength: 0.12236608797684312
  lightness: 0.15863319369964302
  saturation: 0.6869022708851844
  rhythmicContrast: 0.5787777013611048
purpose: []
