name: Already Aware
favicon: null
layout_spectrum: 0.25153
typography_spectrum: 0.43558
title: Already Aware
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242721'
    - '#006b00'
    - '#ffa600'
    - '#e4e684'
    - '#67819d'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
